# Site settings
title: satyānāsh
email: sayajeet aight kanetkar dawt co dawt in
description: I don't know anything.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://satyanash.net" # the base hostname & protocol for your site
twitter_username: SatKanetkar
github_username:  satyanash

# Build settings
markdown: kramdown

plugins:
    - jekyll-sitemap
